config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  # Index, Root or Home
  root 'home#index'

  resources :posts do
    resources :comments
    # va a crear adicionalmente una ruta para publish con el método patch o put (sirven para actualizar) --> ruta personalizada
    member do
      patch :publish
    end
  end

  resources :subscriptors

  ## Admin Routes
  get 'admin', to: 'admin#index'
  get 'admin/products', to: 'admin#products'
  # get 'admin/index'
  # get 'admin/show'

  ##Products routes
  resources :products #a estas rutas tendrá acceso el user
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # #   get 'posts/index', to: 'posts#index'
  # #   get 'posts/create', to: 'posts#create'
  # # # En total 8 rutas. que con resources se crean automáticamente
  
  # # Home Routes
  # #get 'home', to: 'home#index' #sintáxis más común
  # #get '/home/:name', to: 'home#hello' #hello es una nueva acción y :name es una variable de ruta
  # #get 'home/index'
  # get '/home/index', to: 'home#index', as: 'cualquier_cosa' #sintaxis sinónima a la línea anterior, el as es como un alias y sirve para hacer links
  # get '/home/about', to: 'home#about'
  # get '/home/contact_us', to: 'home#contact_us'
  # get '/home/prices', to: 'home#prices'

  #  # Blog Routes
  # get 'blog/index'
  # get 'blog/new'
  # get 'blog/show'
  # get 'blog/edit'
  
 

  # Devise
  devise_for :users # se verifican las rutas con rails routes

  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :students, dependent: :delete_all
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :order_status
  # belongs_to :user
  has_many :order_items, dependent: :delete_all

  before_create :set_order_status
  before_save :update_total

  def calculate_total
    # order_items.collect{ |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
    self.order_items.collect{ |oi| oi.product.price* oi.quantity}.sum
    #self.order_items.collect.sum{|oi| oi.product.price * oi.quantity}
  end

  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_total
    # self[:subtotal] = subtotal #self.subtotal
    self.total = calculate_total
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end
    

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active")
    end
  end
  
  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price] 
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders, dependent: :delete_all
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :delete_all
  
  validates :title, :content, presence: true
  


  ### Ejemplos de validaciones numéricas
  # # phone
  # validates :phone, numericality: {only_integer: true}, 

  # # points
  # validates :points, numericality: {greater_than: 5}
  # validates :points, numericality: {greater_than_or_equal_to: 5}
  # validates :points, numericality: {equal_to: 5}
  # validates :points, numericality: {less_than: 5}
  # validates :points, numericality: {less_than_or_equal_to: 5}
  # validates :points, numericality: {other_than: 5}

  # def published
  #   self.published == true 
  # end

  # # Se utiliza una sintaxis especial para definir este tipo de métodos

  # scope :only_published, -> { where(published: true) } #el where es una consulta a la base de datos
  # scope :popular, -> { where("views > ?", 10) } #Suponemos un campo llamado views que cuenta la cantidad de veces que un usuario ve un artículo. SUponemos que existe el campo views:integer en posts. y llamamos los views más populares o supriores a 10



end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items, dependent: :destroy

    default_scope {where(active: true)}
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :courses, dependent: :delete_all

    ## Ejemplo del uso de los callbacks
    # after_create :print_message

    # private
    #     def print_message
    #         puts "Student created"
    #     end
end

app/models/subscriptor.rb
# == Schema Information
#
# Table name: subscriptors
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subscriptor < ApplicationRecord
    validates :name, :email, presence: true
    
    def capitalize_name
        self.name = self.name.capitalize
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :orders, dependent: :delete_all

  # Para Settear los roles:
  enum role: [:user, :admin]
  before_create :set_default_user

  def set_default_user
    self.role = :user 
  end

  def subscriptor?  #método boolean
    Subscriptor.all.map(&:email).include? self.email # es lo mismo que User.email
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>  

app/views/admin/_posts_table.html.erb
<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th>#Id</th>
                <th>Título</th>
                <th>Autor</th>
                <th>Categoría</th>
                <th>#Comentarios</th>
                <th>Acciones</th>
            </tr>
          </thead>
          <tbody>

          <% @posts.each do |post|%>
            <tr>
                <td><%=post.id%></td>
                <td><%=post.title%></td>
                <td><%=post.user.email%></td>
                <td><%=post.category.name%></td>
                <td><%=post.comments.count%></td>
                <td>

            <div class="btn-group" role="group">
                <%= link_to post_path(post), class:"btn btn-primary" do %>
                    <span data-feather="eye"></span>
                <% end %>

                <%= link_to edit_post_path(post), class: "btn btn-warning" do %>
                    <span data-feather="edit"></span>
                <% end %>

                <%= button_to post_path(post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" do %>
                    <span data-feather="trash-2"></span>
                <% end %>
            </div>
            
                <td>
            </tr>
          <%end %>


           
          </tbody>
        </table>
      </div>

app/views/admin/_row.html.erb
<tr id="<%= product.id%>">
    <td><%=product.id%></td>
    <td><%=product.name%></td>
    <td><%=product.price%></td>
    <td><%=product.active%></td>
</tr>

app/views/admin/_side_navbar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>
         <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/views/admin/_subscriptors_table.html.erb
<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#Id</th>
              <th>Nombre</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>

          <% @subscriptors.each do |subscriptor|%>
            <tr>
              <td><%=subscriptor.id%></td>
              <td><%=subscriptor.name%></td>
              <td><%=subscriptor.email%></td>
            </tr>
          <%end %>


           
          </tbody>
        </table>
      </div>

app/views/admin/_users_table.html.erb
<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#Id</th>
              <th>Email</th>
              <th>Role</th>
              <th>Registrado</th>
            </tr>
          </thead>
          <tbody>

          <% @users.each do |user|%>
            <tr>
              <td><%=user.id%></td>
              <td><%=user.email%></td>
              <td><%=user.role%></td>
              <td><%=user.created_at%></td>
            </tr>
          <%end %>


           
          </tbody>
        </table>
      </div>

app/views/admin/index.html.erb
<%=render 'nav'%>

 <div class="container-fluid">
  <div class="row">
    
    <%= render 'side_navbar'%>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button class="btn btn-sm btn-outline-secondary">Share</button>
            <button class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

       <canvas class="my-4" id="myChart" width="900" height="380"></canvas>
       <h2>Usuarios</h2>
      
        <%= render 'users_table'%>
      
       <hr>
       <h2>Posts</h2>
      
       <%= render 'posts_table'%>

        <hr>
        <h2>Subscriptors</h2>

        <%= render 'subscriptors_table'%>

    </main>
  </div>
</div>
 <!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
 <!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
  feather.replace()
</script>
 <!-- Graphs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ["Users", "Posts", "Comments", "Subscriptors"],
      datasets: [{
        data: [<%= @users.count%>, <%= @posts.count%>, <%=@comments.count%>, <%=@subscriptors.count%>],
        lineTension: 0,
        backgroundColor: 'transparent',
        borderColor: '#007bff',
        borderWidth: 4,
        pointBackgroundColor: '#007bff'
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true
          }
        }]
      },
      legend: {
        display: false,
      }
    }
  });

</script>

app/views/admin/products.html.erb
<%=render 'nav'%>

 <div class="container-fluid">
  <div class="row">
    
    <%= render 'side_navbar'%>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
             <%= link_to "Nuevo Producto", new_product_path, remote: true, class:"btn btn-sm btn-outline-secondary"%>
          </div>
          <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

       <h2>Products</h2>
      
       <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th>#Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Active?</th>
            </tr>
          </thead>
          <tbody>

          <% @products.each do |product|%>
            <%= render 'row', product: product %> <%# Estamos pasando la variable product: si se cambia también debe tener el mismo nombre que en el partial _row%>
          <% end %>
          
          </tbody>
        </table> 
      </div>

    </main>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alerts text-center">
    <% if flash[:notice] %>
        <div class="alert alert-success">
            <%= flash[:notice] %>
        </div>
    <% elsif flash[:alert]%>
        <div class="alert alert-danger">
            <%= flash[:alert] %>
        </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://makeireal.camp/">MakeitReal</a> by <a href="https://twitter.com/you">@you</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Amazon</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav m-auto">
                <li class="nav-item m-auto">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item m-auto">
                    <a class="nav-link" href="/products">Products</a>
                </li>
                <li class="nav-item m-auto">
                    <a class="nav-link" href="/posts">Blog</a>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">
                <%= render 'layouts/sign_in'%>
                <%= link_to "#{current_order.order_items.size} Items in Cart (#{number_to_currency(current_order.total)})", cart_path, class:"btn btn-success btn-sm ml-3"%>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/_sign_in.html.erb
<% if user_signed_in? %>
  <%= link_to "Edit User", edit_user_registration_path, class: "btn btn-sm btn-outline-secondary" %>&nbsp;
  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-danger" %>
  <!-- You are logged in as <%#= current_user.email %> -->
<% else %>
  <%= link_to 'Login', new_user_session_path, class: "btn btn-sm btn-outline-secondary" %>&nbsp;
  <%= link_to 'Register', new_user_registration_path, class: "btn btn-sm btn-outline-primary" %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application - Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%#Alerts%>
    <script>
      $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
      $(".alert").on('clic', '.alert', function(){ $(this).remove() });
    </script>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Application - Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <%= yield %>

    <%#Alerts%>
    <script>
      $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
      $(".alert").on('clic', '.alert', function(){ $(this).remove() });
    </script>

  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login - Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <%= stylesheet_link_tag    'signin', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <%= yield %>
     
     <%#Alerts%>
    <script>
      $(".alert").fadeIn(500).css("opacity", "0.85").delay(6000).slideUp(1000);
      $(".alert").on('clic', '.alert', function(){ $(this).remove() });
    </script>
  </body>
</html>