config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  # Index, Root or Home
  root 'home#index'

  resources :posts do
    resources :comments
    # va a crear adicionalmente una ruta para publish con el método patch o put (sirven para actualizar) --> ruta personalizada
    member do
      patch :publish
    end
  end

  resources :subscriptors

  ## Admin Routes
  get 'admin', to: 'admin#index'
  get 'admin/products', to: 'admin#products'
  # get 'admin/index'
  # get 'admin/show'

  ##Products routes
  resources :products #a estas rutas tendrá acceso el user
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # #   get 'posts/index', to: 'posts#index'
  # #   get 'posts/create', to: 'posts#create'
  # # # En total 8 rutas. que con resources se crean automáticamente
  
  # # Home Routes
  # #get 'home', to: 'home#index' #sintáxis más común
  # #get '/home/:name', to: 'home#hello' #hello es una nueva acción y :name es una variable de ruta
  # #get 'home/index'
  # get '/home/index', to: 'home#index', as: 'cualquier_cosa' #sintaxis sinónima a la línea anterior, el as es como un alias y sirve para hacer links
  # get '/home/about', to: 'home#about'
  # get '/home/contact_us', to: 'home#contact_us'
  # get '/home/prices', to: 'home#prices'

  #  # Blog Routes
  # get 'blog/index'
  # get 'blog/new'
  # get 'blog/show'
  # get 'blog/edit'
  
 

  # Devise
  devise_for :users # se verifican las rutas con rails routes

  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :students, dependent: :delete_all
end

app/models/order.rb
class Order < ApplicationRecord
  # belongs_to :order_status
  # belongs_to :user
  has_many :order_items, dependent: :delete_all

  before_create :set_order_status
  before_save :update_total

  def calculate_total
    # order_items.collect{ |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
    self.order_items.collect{ |oi| oi.product.price* oi.quantity}.sum
    #self.order_items.collect.sum{|oi| oi.product.price * oi.quantity}
  end

  private
  def set_order_status
    self.order_status_id = 1
  end

  def update_total
    # self[:subtotal] = subtotal #self.subtotal
    self.total = calculate_total
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end
    

  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active")
    end
  end
  
  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price] 
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
    has_many :orders, dependent: :delete_all
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :delete_all
  
  validates :title, :content, presence: true
  


  ### Ejemplos de validaciones numéricas
  # # phone
  # validates :phone, numericality: {only_integer: true}, 

  # # points
  # validates :points, numericality: {greater_than: 5}
  # validates :points, numericality: {greater_than_or_equal_to: 5}
  # validates :points, numericality: {equal_to: 5}
  # validates :points, numericality: {less_than: 5}
  # validates :points, numericality: {less_than_or_equal_to: 5}
  # validates :points, numericality: {other_than: 5}

  # def published
  #   self.published == true 
  # end

  # # Se utiliza una sintaxis especial para definir este tipo de métodos

  # scope :only_published, -> { where(published: true) } #el where es una consulta a la base de datos
  # scope :popular, -> { where("views > ?", 10) } #Suponemos un campo llamado views que cuenta la cantidad de veces que un usuario ve un artículo. SUponemos que existe el campo views:integer en posts. y llamamos los views más populares o supriores a 10



end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items, dependent: :destroy

    default_scope {where(active: true)}
end

app/models/student.rb
class Student < ApplicationRecord
    has_and_belongs_to_many :courses, dependent: :delete_all

    ## Ejemplo del uso de los callbacks
    # after_create :print_message

    # private
    #     def print_message
    #         puts "Student created"
    #     end
end

app/models/subscriptor.rb
# == Schema Information
#
# Table name: subscriptors
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subscriptor < ApplicationRecord
    validates :name, :email, presence: true
    
    def capitalize_name
        self.name = self.name.capitalize
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :orders, dependent: :delete_all

  # Para Settear los roles:
  enum role: [:user, :admin]
  before_create :set_default_user

  def set_default_user
    self.role = :user 
  end

  def subscriptor?  #método boolean
    Subscriptor.all.map(&:email).include? self.email # es lo mismo que User.email
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">E-COMMERCE CART</h1>
    </div>
</section>

<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Product</th>
                            <th scope="col" class="text-right">Price</th>
                            <th scope="col" class="text-right">Quantity</th>
                            <th scope="col" class="text-right">Total Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                            <% if  @order_items.any? %>
                            <% @order_items.each do |item| %>

                                <tr>
                                    <td><img src="https://dummyimage.com/50x50/55595c/fff" alt=""></td>
                                    <td class="text-right"><%= item.product.name%></td>
                                    <td class="text-right"><%= number_to_currency(item.product.price)%></td>
                                    <td class="text-right"><%= item.quantity %></td>
                                    <td class="text-right"><%= number_to_currency(item.product.price * item.quantity) %></td>
                                    <td class="text-right">
                                        <%= link_to order_item_path(item), :data => {confirm: "Are you sure?", method: :delete}, class:"btn btn-sm btn-danger" do %>
                                            Delete
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>Shipping</td>
                                <td class="text-right">$0</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>Total</td>
                                <td class="text-right"><strong><%= number_to_currency(current_order.total) %></strong></td>
                            </tr>
                        <% else %>
                            <p> Your Cart is empty </p>
                        <% end %>
                    </tbody>
                </table>
                <%= link_to "Checkout", root_path, class: "btn btn-success btn-lg" %>
            </div>
        </div>
    </div>
</div>