config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  # Index, Root or Home
  root 'home#index'

  resources :posts do
    resources :comments
    # va a crear adicionalmente una ruta para publish con el método patch o put (sirven para actualizar) --> ruta personalizada
    member do
      patch :publish
    end
  end

  resources :subscriptors

  ## Admin Routes
  get 'admin', to: 'admin#index'
  get 'admin/products', to: 'admin#products'
  # get 'admin/index'
  # get 'admin/show'

  ##Products routes
  resources :products #a estas rutas tendrá acceso el user
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  # #   get 'posts/index', to: 'posts#index'
  # #   get 'posts/create', to: 'posts#create'
  # # # En total 8 rutas. que con resources se crean automáticamente
  
  # # Home Routes
  # #get 'home', to: 'home#index' #sintáxis más común
  # #get '/home/:name', to: 'home#hello' #hello es una nueva acción y :name es una variable de ruta
  # #get 'home/index'
  # get '/home/index', to: 'home#index', as: 'cualquier_cosa' #sintaxis sinónima a la línea anterior, el as es como un alias y sirve para hacer links
  # get '/home/about', to: 'home#about'
  # get '/home/contact_us', to: 'home#contact_us'
  # get '/home/prices', to: 'home#prices'

  #  # Blog Routes
  # get 'blog/index'
  # get 'blog/new'
  # get 'blog/show'
  # get 'blog/edit'
  
 

  # Devise
  devise_for :users # se verifican las rutas con rails routes

  
  

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :delete_all
  
  validates :title, :content, presence: true
  


  ### Ejemplos de validaciones numéricas
  # # phone
  # validates :phone, numericality: {only_integer: true}, 

  # # points
  # validates :points, numericality: {greater_than: 5}
  # validates :points, numericality: {greater_than_or_equal_to: 5}
  # validates :points, numericality: {equal_to: 5}
  # validates :points, numericality: {less_than: 5}
  # validates :points, numericality: {less_than_or_equal_to: 5}
  # validates :points, numericality: {other_than: 5}

  # def published
  #   self.published == true 
  # end

  # # Se utiliza una sintaxis especial para definir este tipo de métodos

  # scope :only_published, -> { where(published: true) } #el where es una consulta a la base de datos
  # scope :popular, -> { where("views > ?", 10) } #Suponemos un campo llamado views que cuenta la cantidad de veces que un usuario ve un artículo. SUponemos que existe el campo views:integer en posts. y llamamos los views más populares o supriores a 10



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] #Vamos a exigir que el usuario esté loggeado para poder ingresar a show, sino no puede entrar
  #before_action :validate_user, only: [:edit, :update, :destroy]
  before_action :is_admin?, only: [:edit, :update, :destroy]


  def index
    if params[:category].blank? #también se puede usar .present?
      @posts = Post.all.order(created_at: :desc).paginate(page: params[:page], per_page: 2)
      #@posts = current_user.posts
      @last_post = Post.last #Esta variable la creo con el obj de renderizarla en _jumbotron
      @category = Category.all

      @shoes_category = Category.find_by(name: "Shoes")
      @shoes_last_post = @shoes_category.posts.last

      @woman_category = Category.find_by(name: "Woman")
      @woman_last_post = @woman_category.posts.last
    else
    @category_id = Category.find_by(name: params[:category]).id
    @posts = Post.where(category_id: @category_id)
                 .order(created_at: :desc)
                 .paginate(page: params[:page], per_page: 2)
    end
  end

  def new
    @post = Post.new  #Crea un objeto nuevo
  end

  def create
    @post = Post.new(post_params)  #Esta ruta viene ligada con el método post, donde se crea el númevo post
    #post_params es un método que debe ir creado como un método privado, ya que lo ideal es que desde afuera no nos llamen este método. Evitar usuarios maliciosos que creen por JS otros campos
    @post.user = current_user  # lo del current_user está dentro de la gem devise

    if @post.save
      # send email to users with new post
      title = @post.title
      id = @post.id
      
      users = User.where(role: "user")
      subscriptors = Subscriptor.all

      users.each do |user|
        email = user.email
        type_user = "User"
        UserNotifierMailer.new_post_notifying(email, title, id, type_user).deliver_now
      end

      subscriptors.each do |subscriptor|
        email = subscriptor.email
        type_user = "Subscriptor"
        UserNotifierMailer.new_post_notifying(email, title, id, type_user).deliver_now
      end

      ## con el código de 
      #   UserNotifierMailer.new_post_notifying_user(user_email, title, id).deliver_nowarriba se refactorizó el siguiente: también se modificó en user_notifier_mailer.rb y se agregó la view con el método new_post_notifying.html.erb
      # users.each do |user|
      #   user_email = us
      #   UserNotifierMailer.new_post_notifying_user(user_email, title, id).deliver_nower.email
      #   UserNotifierMailer.new_post_notifying_user(user_email, title, id).deliver_now
      # end

      # subscriptors.each do |subscriptor|
      #   subscriptor_email = subscriptor.email
      #   UserNotifierMailer.new_post_notifying_subscriptor(subscriptor_email, title, id).deliver_now
      # end

      redirect_to posts_path, notice: "Post created successfully"
    else
      flash[:alert] = "Post failed to be created. Try again"
      render :new
    end

  end

  def show
    @post = Post.find(params[:id]) #Lo nombro en singular ya que sólo voy a mostrar un post (usamos .find y no con .find_by ya que recibimos un id por la URL)
    @comments = @post.comments.order(created_at: :desc).paginate(page: params[:page], per_page: 2)
    

  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      ## enviar un correo nuevo a los users y subscriptors cuando se edita un nuevo post
      title = @post.title
      id = @post.id   
      users = User.where(role: "user")
      subscriptors = Subscriptor.all

      users.each do |user|
        email = user.email
        type_user = "User"
        UserNotifierMailer.update_post_notifying(email, title, id, type_user).deliver_now
      end

      subscriptors.each do |subscriptor|
        email = subscriptor.email
        type_user = "Subscriptor"
        UserNotifierMailer.update_post_notifying(email, title, id, type_user).deliver_now
      end



      redirect_to posts_path, notice: "Post updated successfully"
    else
      render :edit, alert: "Post failed to be edited. Try again"
    end

  end

  def destroy
    post = Post.find(params[:id]) #No se utiliza variables de instancia ya que se elimina desde la misma página
    post.destroy
    ## Otra forma de escribir el flash notice y el flash alert
    #flash[:notice] = "El post fue eliminado exitosamente"

    redirect_to posts_path, notice: "Post deleted successfully"
  end

  def publish
    sleep 2 # método de ruby que va a dormir la petición por 2 segundos
    @post = Post.find(params[:id])
    @post.update(published_at: Time.zone.now)
  end

  private
    def post_params
      params.require(:post).permit(:user_id, :title, :content, :category_id, :published_at)
    end

    # def validate_user
    #   unless current_user.posts.ids.to_s.include? params[:id]
    #     redirect_to root_path
    #     flash[:alert] = "You don't have permissions"
    #   end
    # end

    def is_admin?
      unless current_user.admin?
        flash[:alert] = "You don't have permissions"
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_comment.html.erb
<h2>Add Comment</h2>

<%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="form-group">
        <label for="">Comment</label>
            <%= f.text_area :comment, class: "form-control" %>
    
        <p>
            <%= f.button "Save Comment", class:"btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Publishing..."} %>
        </p>
    </div>
<% end %>

app/views/posts/_cards.html.erb
<div class="row mb-2">
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-primary"><%=@shoes_category.name%></strong>
          <h3 class="mb-0">
            <%= link_to @shoes_last_post.title, post_path(@shoes_last_post), class:"text-dark"%>
          </h3>
          <div class="mb-1 text-muted"><%= time_ago_in_words @shoes_last_post.created_at%> ago</div>
          <p class="card-text mb-auto">
          <%= @shoes_last_post.content.length > 140 ? @shoes_last_post.content.truncate(140)  : @shoes_last_post.content%>
          </p>
          <%= link_to "Continue reading...", post_path(@shoes_last_post.id)%>
        </div>
        <%= image_tag('download.jpg', class: "card-img-right flex-auto d-none d-md-block")  %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="card-body d-flex flex-column align-items-start">
          <strong class="d-inline-block mb-2 text-success"><%=@woman_category.name%></strong>
          <h3 class="mb-0">
            <%= link_to @woman_last_post.title, post_path(@woman_last_post), class:"text-dark"%>
          </h3>
          <div class="mb-1 text-muted"><%= time_ago_in_words @woman_last_post.created_at%> ago</div>
          <p class="card-text mb-auto">
          <%= @woman_last_post.content.length > 140 ? @woman_last_post.content.truncate(140)  : @woman_last_post.content%>
          </p>
          <%= link_to "Continue reading...", post_path(@woman_last_post)%>
        </div>
        <%= image_tag('download.jpg', class: "card-img-right flex-auto d-none d-md-block")  %>
        
      </div>
    </div>
  </div>
</div>

app/views/posts/_categories.html.erb
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <% Category.all.each do |category|%>
      <%#<a class="p-2 text-muted" href="#"><%=category.name%>
      <%= link_to category.name, posts_path(category: category.name), class:"p-2 text-muted"%>
    <% end %>
    </nav>
  </div>

app/views/posts/_comments.html.erb
<div class="p-3 mb-3 bg-light rounded" id="comments"">
    <h4 class="font-italic">Comments</h4>
    <% @comments.each do |comment|%>

        <p class="mb-0">
            <%= comment.user.email %>
            <strong>Comment: </strong>
            <%= comment.comment %></li>
        </p>
        <br>

    <% end %>

</div>

<nav class="blog-pagination">
        <%= will_paginate @comments, params: { anchor: "comments" }, previous_label: '&laquo;', next_label: '&raquo;' %>
</nav>

app/views/posts/_form.html.erb
<%#= form_for @post do |f| %>
<%#<div>
        <%#= f.label :title%>
<%#= f.text_field :title%>
<%#</div>
    
    <%#<div>
        <%#= f.label :content%>
<%#= f.text_area :content%>
<%#</div>

        <%# f.check_box :content%>
<%# f.radio_button :content%>
<%# f.date_field :nombre_campo%>
<%# f.password_field :name_campo%>
<%# f.email_field :name_campo%>
<%# f.hidden_fiel :name_campo%>
<%# f.collection_select(:city_id, City.all, :id, :name)%>

<%#<div>
        <%#= f.submit%>
<%#</div>


<%# end %>

<%# Formulario no asociados a la db, ya que no me comunico con ningun modelo, todo lo pasa como un query string%>
<%#= form_tag("/search", method: "get") do %>
<%#= label_tag(:q, "Search for:") %>
<%#= text_field_tag(:q) %>
<%#= submit_tag("Search") %>
<%# end %>


<div class="container">
  <%= render 'header'%>
  <%= render 'categories'%>
  <%= render 'layouts/alerts' %>
</div>

<main role="main" class="container mt-4">
  <div class="row">
    <div class="col-md-12 blog-main">
      <hr>
      <div class="blog-post">
        <% unless @post.new_record? %>
        <h2 class="blog-post-title">
          <%= @post.title %>
        </h2>
        <p class="blog-post-meta">
          <%= time_ago_in_words(@post.created_at) %> ago by <a href="#">
            <%= @post.user.email %></a></p>
        <% end %>

        <p>


          <%= form_for @post do |f| %>

          <% if @post.errors.any?%>
          <div class="alert alert-danger alert-block alert-fized">
            <p>
              <%= pluralize(@post.errors.count, "error")%>
              prevent this post from saving
            </p>
            <ul>
              <% @post.errors.full_messages.each do |msg|%>
              <li>
                <%= msg %>
              </li>
              <% end %>
            </ul>
          </div>
          <% end %>

          <div class="form-group">
            <label>Category</label>
            <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "Choose a Category" }, {class: "form-control" })  %>
          </div>
          <div class="form-group">
            <label for="exampleFormControlInput1">Title</label>
            <%= f.text_field :title, class: "form-control"  %>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Content</label>
            <%= f.text_area :content, class: "form-control" %>
          </div>
          <%= f.button class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Publishing..."} %>
          <% end %>

        </p>

      </div><!-- /.blog-post -->

    </div><!-- /.blog-main -->


  </div><!-- /.row -->

</main><!-- /.container -->

<%= render "layouts/footer" %>

app/views/posts/_jumbotron.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic"><%=@last_post.title%></h1>

      <%if @last_post.content.length > 140 %>
            <%= truncate(@last_post.content, length: 140) %>
            <%= link_to "Continue reading...", post_path(@last_post.id), class:"text-white font-weight-bold"%>
          <% else %>
            <%= @last_post.content %>
          <% end %>    

          <%#= @last_post.content.length > 140 ? @last_post.content.truncate(140) : @last_post.content%>
    </div>
  </div>

  

<%= render "cards" %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <%=render 'header'%>

  <%= render 'categories'%>

  <%= render 'layouts/alerts' %>

<% unless params[:category].present?%>
  <%=render 'jumbotron'%>
<%end%>
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-3 mb-4 font-italic border-bottom" id="posts">
        <% if params[:category].blank?%>
          From the Firehose
        <%else%>
          Search by: <%= params[:category]%>
        <% end %>
      </h3>

      <% @posts.each do |post| %>
        <div class="blog-post">
          <h2 class="blog-post-title"><%= link_to post.title, post_path(post.id), class:"text-muted", style: "text-decoration:none" %></h2>
          <p class="blog-post-meta"><%= time_ago_in_words(post.created_at) %> ago by <a href="#"><%= post.user.email %></a>
          Category: <%= post.category.name%>
          </p>
          <p>
          
          <!-- /Este condicional es para truncar o cortar una cadena para mostrar cierta cantidad de caracteres en el index -->
          <%if post.content.length > 250 %>
            <%= truncate(post.content, length: 250) %>
            <%= link_to "... Read more", post_path(post.id)%>
          <% else %>
            <%= post.content %>
          <% end %>          
          
          </p>
        </div><!-- /.blog-post -->
      <% end %>


      <nav class="blog-pagination">
        <%= will_paginate @posts, params: { anchor: "posts" }, previous_label: '&laquo;', next_label: '&raquo;' %>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-3 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-3">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main><!-- /.conta»
iner -->

<%= render "layouts/footer" %>

<script>
  new ProductView();
</script>

app/views/posts/new.html.erb
<!--form class="" action="" method="">

</form> Usamos unos helpers de RAILS-->

<%= render 'form' %>

app/views/posts/otros.html.erb
<h1>Posts</h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "Crear nuevo post", new_post_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Title</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.user.email %></td>
        <td><%= post.title %></td>
        <td>
          <%#= link_to "Texto que va a aparecer", ruta_path, method, class %>
          <%= link_to "Mostrar", post_path(post) %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "Editar", edit_post_path(post) %>
            <%= link_to "Eliminar", post_path(post), method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/publish.js.erb
// alert('Hello')
$('#published-at').text('<%= @post.published_at%>');

app/views/posts/show.html.erb
<div class="container">
  <%= render 'header'%>

<%= render 'categories'%>

<%= render 'layouts/alerts' %>

</div>

<main role="main" class="container mt-4">
  <div class="row">
    <div class="col-md-12 blog-main">
      <hr>
        <div class="blog-post">
          <h2 class="blog-post-title"><%= @post.title %></h2>
          <p class="blog-post-meta"><%= time_ago_in_words(@post.created_at) %> ago by <a href="#"><%= @post.user.email %></a> 
          Category: <%= @post.category.name %>
          Published At: <span id="published-at"><%= @post.published_at %></span>
          </p>
          <p>
            <% if user_signed_in? && current_user.admin? %>
              <%= link_to "Publish", publish_post_path(@post), method: :patch, remote: true, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>&nbsp;&nbsp;Publishing..."}, class: "btn btn-warning"%>
              <%= link_to "Editar", edit_post_path(@post), class: "btn btn-primary" %>
              <%= link_to "Eliminar", post_path(@post), method: :delete, data: {confirm: "Are you sure?", disable_with: "<i class='fa fa-spinner fa-spin'></i>&nbsp;&nbsp;Removing..."}, class: "btn btn-danger" %>
            <% end %>
          </p>
          <p>
            <%= @post.content %>
          </p>
        </div><!-- /.blog-post -->

        <% if @post.comments.exists? %>
        <%#= render "comments/comments" %>
          <%= render 'comments' %>
        <% end %>


        <%#= render 'comments/form'%>
        <%= render 'add_comment' %>

        <br>


    </div><!-- /.blog-main -->


  </div><!-- /.row -->

</main><!-- /.container -->

<%= render "layouts/footer" %>